"""Paid by

Revision ID: 19621e344e7d
Revises: 0f9bd44318b8
Create Date: 2023-01-01 14:01:50.527208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19621e344e7d'
down_revision = '0f9bd44318b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
