"""Last Sent

Revision ID: df6c64d8eb7f
Revises: eb21eb40a1f7
Create Date: 2023-01-01 14:20:36.383931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6c64d8eb7f'
down_revision = 'eb21eb40a1f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('lastInvoiceSent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'lastInvoiceSent')
    # ### end Alembic commands ###
