"""Paid by

Revision ID: eb21eb40a1f7
Revises: 19621e344e7d
Create Date: 2023-01-01 14:03:51.257979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb21eb40a1f7'
down_revision = '19621e344e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('paidAt', sa.DateTime(), nullable=True))
    op.add_column('debts', sa.Column('paidAmount', sa.Float(), nullable=True))
    op.add_column('debts', sa.Column('paidBy', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debts', 'paidBy')
    op.drop_column('debts', 'paidAmount')
    op.drop_column('debts', 'paidAt')
    # ### end Alembic commands ###
