"""Auto Increment

Revision ID: 0f9bd44318b8
Revises: 90dbd296d804
Create Date: 2022-12-27 17:31:37.148005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9bd44318b8'
down_revision = '90dbd296d804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
