"""Added debts table

Revision ID: 90dbd296d804
Revises: da9a266bd47d
Create Date: 2022-12-25 16:55:49.125717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dbd296d804'
down_revision = 'da9a266bd47d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('governmentId', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('debtAmount', sa.Float(), nullable=False),
    sa.Column('debtDueDate', sa.DateTime(), nullable=False),
    sa.Column('debtId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('debtId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debts')
    # ### end Alembic commands ###
